### PR TITLE
adds poetry, pytest

### PR DESCRIPTION
**Pull request by datajango**
- Adds poetry for development
- Adds pytest
- Adds a DEV,md for developer instructions

### CODE REVIEW

**Comment by datajango** [comment]
Will hold off until we talk. There are significant problems with re-wx that I just became aware of.

**Comment by jamesdbrock** [comment]
I for one would like to hear about what problems you’re thinking of.

**Comment by bkZHD** [comment]
Me too!

**Comment by datajango** [comment]
Hi Guys.  Before I jump in to this noble effort with you I thought  we should discuss the future of re-wx,   Let's start with a complex control https://github.com/chriskiehl/re-wx/issues/24 and see where it leads us.

**Pull request closed without merging**
